#!/usr/bin/env python3
"""Refresh site/assets/data/posts.js with the public posts of a Velog blog.

Usage:  python3 scripts/update-posts.py [velog-username]

Reads the list of released posts from Velog's public GraphQL endpoint. Only titles, slugs
and release dates are kept. The result is written as a plain script (not JSON) so the page
also works when index.html is opened straight from disk.
"""
import json
import sys
import urllib.request
from datetime import date
from pathlib import Path

login = sys.argv[1] if len(sys.argv) > 1 else "jayaione_ele"
QUERY = (
    "query Posts($username: String, $limit: Int, $cursor: ID) "
    "{ posts(username: $username, limit: $limit, cursor: $cursor) { id title url_slug released_at } }"
)


def page(cursor):
    body = json.dumps({"query": QUERY, "variables": {"username": login, "limit": 50, "cursor": cursor}}).encode()
    req = urllib.request.Request(
        "https://v2.velog.io/graphql",
        data=body,
        headers={"Content-Type": "application/json", "User-Agent": "Mozilla/5.0"},
    )
    with urllib.request.urlopen(req, timeout=20) as res:
        data = json.load(res)
    if data.get("errors"):
        raise SystemExit(f"Velog returned errors: {data['errors'][:1]}")
    return data["data"]["posts"]


posts, cursor = [], None
while True:
    chunk = page(cursor)
    if not chunk:
        break
    posts += chunk
    cursor = chunk[-1]["id"]
    if len(chunk) < 50:
        break

if not posts:
    raise SystemExit("No posts came back. Keeping the current file.")

posts.sort(key=lambda p: p["released_at"], reverse=True)
payload = {
    "login": login,
    "updated": date.today().isoformat(),
    "total": len(posts),
    "posts": [{"t": p["title"], "s": p["url_slug"], "d": p["released_at"][:10]} for p in posts],
}

out = Path(__file__).resolve().parent.parent / "site" / "assets" / "data" / "posts.js"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(
    "// Generated by scripts/update-posts.py. Do not edit by hand.\n"
    "window.POSTS = " + json.dumps(payload, ensure_ascii=False, separators=(",", ":")) + ";\n",
    encoding="utf-8",
)
print(f"{out}: {len(posts)} posts ({posts[-1]['released_at'][:10]} to {posts[0]['released_at'][:10]})")
