#!/usr/bin/env python3
"""Refresh site/assets/data/contributions.js with the last year of GitHub contributions.

Usage:  python3 scripts/update-contributions.py [github-login]

The values come from github-contributions-api.jogruber.de, which mirrors the calendar
shown on the public GitHub profile. Nothing private is read. The result is written as a
plain script (not JSON) so the page also works when index.html is opened straight from disk.
"""
import json
import sys
import urllib.request
from datetime import date
from pathlib import Path

login = sys.argv[1] if len(sys.argv) > 1 else "JiwonLee42"
url = f"https://github-contributions-api.jogruber.de/v4/{login}?y=last"

with urllib.request.urlopen(url, timeout=20) as res:
    data = json.load(res)

days = data["contributions"]
payload = {
    "login": login,
    "updated": date.today().isoformat(),
    "start": days[0]["date"],
    "total": data["total"]["lastYear"],
    "counts": [d["count"] for d in days],
    "levels": "".join(str(d["level"]) for d in days),
}

out = Path(__file__).resolve().parent.parent / "site" / "assets" / "data" / "contributions.js"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(
    "// Generated by scripts/update-contributions.py. Do not edit by hand.\n"
    "window.CONTRIBUTIONS = " + json.dumps(payload, separators=(",", ":")) + ";\n",
    encoding="utf-8",
)
print(f"{out}: {len(days)} days, {payload['total']} contributions ({payload['start']} to {days[-1]['date']})")
